apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: santhhoshkumar/python:17
        name: flaskdemo
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer  # Use NodePort instead of LoadBalancer
  ports:
  - port: 80           # The port exposed within the cluster
    targetPort: 80    # The port on which your Flask app is running inside the container
  #  nodePort: 30080     # Optional: specify a static port from the NodePort range (30000-32767)
  selector:
    app: flaskdemo
